name: GitHub Container Registry Cleanup
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          package: webmap
          registry-url: ghcr.io
          delete-tags: "*"
          exclude-tags: latest
          delete-untagged: true